#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# routes.yaml
app_social_media_admin:
  path: /backoffice/socialMedia
  controller: App\Controller\SocialMediaAdminController::index

app_social_media_chart_data:
  path: /backoffice/socialMedia/chart_data
  controller: App\Controller\SocialMediaAdminController::chartData

app_posts_data:
  path: /backoffice/posts/data
  controller: App\Controller\SocialMediaAdminController::getPostsData

app_commentaire_index:
  path: /commentaire
  controller: App\Controller\CommentaireController::index

app_commentaire_new:
  path: /commentaire/new
  controller: App\Controller\CommentaireController::new

app_commentaire_show:
  path: /commentaire/show/{id}
  controller: App\Controller\CommentaireController::show

app_commentaire_edit:
  path: /commentaire/{id}/edit
  controller: App\Controller\CommentaireController::edit

app_commentaire_delete:
  path: /commentaire/delete/{id}
  controller: App\Controller\CommentaireController::delete

app_get_comments:
  path: /commentaire/get_comments
  controller: App\Controller\CommentaireController::getComments

app_get_comments_pdf:
  path: /commentaire/get_comments_pdf
  controller: App\Controller\CommentaireController::getCommentsForPDF
