# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    your_images_directory: '%kernel.project_dir%/public/images'
    image_dir: "%kernel.project_dir%/public/uploads/images/ingredient "

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    Symfony\Component\Mailer\EventListener\MessageListener:
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Mailer\Event\MessageEvent, method: handleRender }
    Symfony\Component\Mailer\EventListener\EnvelopeListener: ~
    Symfony\Component\Mailer\EventListener\LoggerListener: ~
    Symfony\Component\Mailer\EventListener\SendListener: ~
    Symfony\Bridge\Twig\Mime\BodyRenderer: ~

    App\:
      resource: "../src/"
      exclude:
        - "../src/DependencyInjection/"
        - "../src/Entity/"
        - "../src/Kernel.php"
    App\Entity\InformationPersonnele:
      autowire: true

    App\Entity\Poste:
      autowire: true

    App\Entity\Commentaire:
      autowire: true

    App\Repository\PosteRepository:
      autowire: true

    # Define the CommentaireRepository service
    App\Repository\CommentaireRepository:
      autowire: true
      # factory: ["@doctrine.orm.entity_manager", getRepository]
      # arguments:
      #   - App\Entity\Commentaire
      # factory: ["@doctrine.orm.entity_manager", getRepository]
      # arguments: ['App\Entity\Commentaire']
      # arguments:
      #   $class: Doctrine\ORM\EntityRepository
      #   $class: 'Doctrine\ORM\Mapping\ClassMetadata'
      # class: App\Repository\CommentaireRepository
      # factory: ["@doctrine.orm.entity_manager", getRepository]
      # arguments: [App\Entity\Commentaire]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Psr\Http\Client\ClientInterface:
      class: GuzzleHttp\Client
    Psr\Http\Message\RequestFactoryInterface:
      class: Nyholm\Psr7\Factory\Psr17Factory
    Psr\Http\Message\StreamFactoryInterface:
      class: Nyholm\Psr7\Factory\Psr17Factory
